/**
 * Cities and major localities in Tunisia, grouped by governorate (24 wilayas).
 * Used for event creation, artist profiles, and browse filters.
 */
export type TunisiaCityGroup = {
  governorate: string;
  cities: readonly string[];
};

export const TUNISIA_CITY_GROUPS: readonly TunisiaCityGroup[] = [
  {
    governorate: 'Tunis',
    cities: [
      'Tunis',
      'Le Bardo',
      'La Marsa',
      'Carthage',
      'La Goulette',
      'Le Kram',
      'Sidi Bou Saïd',
      'Sidi Hassine',
      'Ettahrir',
      'Kabaria',
      'Sijoumi',
      'Omrane',
      'Omrane Supérieur',
      'El Ouardia',
      'Ezzouhour',
      'Médina',
    ],
  },
  {
    governorate: 'Ariana',
    cities: [
      'Ariana',
      'La Soukra',
      'Raoued',
      'Ettadhamen',
      'Mnihla',
      'Sidi Thabet',
      'Kalaat el-Andalous',
      'Soukra',
    ],
  },
  {
    governorate: 'Ben Arous',
    cities: [
      'Ben Arous',
      'El Mourouj',
      'Radès',
      'Hammam Lif',
      'Ezzahra',
      'Mégrine',
      'Mohamedia',
      'Fouchana',
      'Mornag',
      'Boumhel el-Bassatine',
      'Mégrine Chaker',
      'Nouvelle Médina',
    ],
  },
  {
    governorate: 'Manouba',
    cities: [
      'Manouba',
      'Douar Hicher',
      'Oued Ellil',
      'Tebourba',
      'Mornaguia',
      'Borj El Amri',
      'Djedeida',
      'El Battan',
      'Jedeida',
    ],
  },
  {
    governorate: 'Nabeul',
    cities: [
      'Nabeul',
      'Hammamet',
      'Kelibia',
      'Korba',
      'Grombalia',
      'Beni Khalled',
      'Menzel Temime',
      'Soliman',
      'Takelsa',
      'Béni Khiar',
      'Dar Chaabane',
      'El Haouaria',
      'Mrezga',
      'Yasmine Hammamet',
    ],
  },
  {
    governorate: 'Zaghouan',
    cities: ['Zaghouan', 'Zriba', 'Fahs', 'Nadhour', 'Saouaf', 'El Fahs'],
  },
  {
    governorate: 'Bizerte',
    cities: [
      'Bizerte',
      'Menzel Bourguiba',
      'Mateur',
      'Sejnane',
      'Ras Jebel',
      'Utique',
      'Menzel Jemil',
      'Tinja',
      'Ghar El Melh',
      'El Alia',
      'Joumine',
      'Ghezala',
    ],
  },
  {
    governorate: 'Béja',
    cities: [
      'Béja',
      'Testour',
      'Nefza',
      'Medjez el-Bab',
      'Amdoun',
      'Teboursouk',
      'Thibar',
      'Goubellat',
      'El Maagoula',
    ],
  },
  {
    governorate: 'Jendouba',
    cities: [
      'Jendouba',
      'Tabarka',
      'Aïn Draham',
      'Fernana',
      'Bou Salem',
      'Ghardimaou',
      'Balta-Borguiba',
      'Oued Meliz',
    ],
  },
  {
    governorate: 'Le Kef',
    cities: [
      'Le Kef',
      'Dahmani',
      'Sakiet Sidi Youssef',
      'Tajerouine',
      'Kalaat Senan',
      'Sers',
      'Nebeur',
      'El Ksour',
      'Jerissa',
    ],
  },
  {
    governorate: 'Siliana',
    cities: [
      'Siliana',
      'Bou Arada',
      'Gaâfour',
      'El Aouinet',
      'Kesra',
      'Makthar',
      'Rouhia',
      'Bargou',
      'El Krib',
    ],
  },
  {
    governorate: 'Sousse',
    cities: [
      'Sousse',
      'Msaken',
      'Enfidha',
      'Hammam Sousse',
      'Kalaa Kebira',
      'Kalaa Sghira',
      'Hergla',
      'Sidi Bou Ali',
      'Port El Kantaoui',
      'Akouda',
      'Bouficha',
      'Messaadine',
      'Sidi El Heni',
      'Kondar',
      'Zaouiet Sousse',
    ],
  },
  {
    governorate: 'Monastir',
    cities: [
      'Monastir',
      'Moknine',
      'Jemmal',
      'Sahline',
      'Ksar Hellal',
      'Teboulba',
      'Bekalta',
      'Lamta',
      'Sayada',
      'Bou Hajar',
      'Ouerdanine',
      'Zéramdine',
      'Beni Hassen',
    ],
  },
  {
    governorate: 'Mahdia',
    cities: [
      'Mahdia',
      'Chebba',
      'El Jem',
      'Ksour Essef',
      'Melloulech',
      'Sidi Alouane',
      'Chorbane',
      'Hbira',
      'Bou Merdes',
      'Chouamacha',
    ],
  },
  {
    governorate: 'Sfax',
    cities: [
      'Sfax',
      'Agareb',
      'Bir Ali Ben Khalifa',
      'El Amra',
      'El Hencha',
      'Graïba',
      'Jebiniana',
      'Kerkennah',
      'Mahrès',
      'Skhira',
      'Thyna',
      'Chihia',
      'Gremda',
      'Sakiet Ezzit',
      'Sakiet Eddaïer',
      'El Ain',
    ],
  },
  {
    governorate: 'Kairouan',
    cities: [
      'Kairouan',
      'Sbikha',
      'Haffouz',
      'Oueslatia',
      'Hajeb El Ayoun',
      'Nasrallah',
      'Cherarda',
      'Echrarda',
      'Bou Hajla',
      'El Alaa',
    ],
  },
  {
    governorate: 'Kasserine',
    cities: [
      'Kasserine',
      'Sbeitla',
      'Thala',
      'Fériana',
      'Foussana',
      'Haïdra',
      'El Ayoun',
      'Jedeliane',
      'Majel Bel Abbès',
      'Hidra',
      'Ezzouhour (Kasserine)',
    ],
  },
  {
    governorate: 'Sidi Bouzid',
    cities: [
      'Sidi Bouzid',
      'Regueb',
      'Meknassy',
      'Bir el Hafey',
      'Cebbala Ouled Asker',
      'Jilma',
      'Sidi Ali Ben Aoun',
      'Menzel Bouzaiane',
      'Ouled Haffouz',
      'Souk Jedid',
    ],
  },
  {
    governorate: 'Gabès',
    cities: [
      'Gabès',
      'Matmata',
      'El Hamma',
      'Ghannouch',
      'Mareth',
      'Métouia',
      'Nouvelle Matmata',
      'Chenini Nahal',
      'Zarat',
    ],
  },
  {
    governorate: 'Médenine',
    cities: [
      'Médenine',
      'Djerba (Houmt Souk)',
      'Midoun',
      'Ajim',
      'Zarzis',
      'Ben Gardane',
      'Beni Khedache',
      'Sidi Makhlouf',
      'Guellala',
    ],
  },
  {
    governorate: 'Tataouine',
    cities: [
      'Tataouine',
      'Remada',
      'Ghomrassen',
      'Bir Lahmar',
      'Dehiba',
      'Smar',
      'Chenini (Tataouine)',
      'Dhehiba',
    ],
  },
  {
    governorate: 'Gafsa',
    cities: [
      'Gafsa',
      'Métlaoui',
      'Redeyef',
      'Moulares',
      'El Ksar',
      'Sidi Aïch',
      'Mdhilla',
      'Sned',
      'El Guettar',
      'Belkhir',
    ],
  },
  {
    governorate: 'Tozeur',
    cities: ['Tozeur', 'Nefta', 'Degache', 'Hazaoua', 'Tamaghza', 'Tameghza'],
  },
  {
    governorate: 'Kébili',
    cities: ['Kébili', 'Douz', 'Souk Lahad', 'Jemna', 'Faouar', 'El Golâa'],
  },
] as const;

/** Flat list of all cities, sorted alphabetically (French locale). */
export const TUNISIA_CITIES: string[] = Array.from(
  new Set(TUNISIA_CITY_GROUPS.flatMap((g) => g.cities))
).sort((a, b) => a.localeCompare(b, 'fr', { sensitivity: 'base' }));

export const DEFAULT_TUNISIA_CITY = 'Tunis';
